name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [main]  # Deploys on push to main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Copy build to root (overwrite repo root with dist)
        run: |
          cp -r dist/* ./
          touch .nojekyll
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "deploy: overwrite with build output"
          git push
